name: Generate Snake Contribution Grid
on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta la acción todos los días a medianoche UTC

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: JulRiv07
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the animation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
